using System.Text.RegularExpressions;

namespace Payment.Processor.Utilities
{
    /// <summary>
    /// A partial class that allows .Net to generate assembly code for the contained Regex.
    /// </summary>
    public static partial class Matchers
    {
        /// <summary>
        /// A method definition representing a Regex to be generated by .Net.
        /// </summary>
        /// <returns></returns>
        [GeneratedRegex(@"^\d+\b")]
        public static partial Regex AddressMatcher();
    }
}
